CREATE TABLE `comment` (
	`comment_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`post_id` BIGINT(20) NULL DEFAULT NULL,
	`url` VARCHAR(2000) NULL DEFAULT NULL,
	`parent` VARCHAR(20) NULL DEFAULT NULL,
	`message` TEXT NULL,
	`media` VARCHAR(1000) NULL DEFAULT NULL,
	`status` VARCHAR(11) NULL DEFAULT NULL,
	`rating` INT(11) NULL DEFAULT NULL,
	`user_agent` VARCHAR(1000) NULL DEFAULT NULL,
	`ip` VARCHAR(39) NULL DEFAULT NULL,
	`author_name` VARCHAR(60) NULL DEFAULT NULL,
	`author_email` VARCHAR(100) NULL DEFAULT NULL,
	`author_www` VARCHAR(200) NULL DEFAULT NULL,
	`author_avatar` VARCHAR(200) NULL DEFAULT NULL,
	`author_provider` VARCHAR(32) NULL DEFAULT NULL,
	`anonym_name` VARCHAR(60) NULL DEFAULT NULL,
	`anonym_email` VARCHAR(100) NULL DEFAULT NULL,
	`created` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`comment_id`)
);
CREATE TABLE `common` (
	`common_name` VARCHAR(50) NULL DEFAULT NULL,
	`common_value` VARCHAR(50) NULL DEFAULT NULL
)